version: '2.1'
services:
    mariadb:
      image: mariadb:latest
      container_name: mariadb
      volumes:
        - mariadb_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: osticket
        MYSQL_USER: osticket
        MYSQL_PASSWORD: osticket_password
      ports:
        - "3307:3306"
      command: --bind-address=mariadb
    
    osticket:
        image: eveanwarl0ck/osticket_1_18_x:0.1
        container_name: osticket
        volumes:
          - osticket_data:/var/www/html/osTicket
        restart: always
        ports:
            - "8080:80"
volumes:
  mariadb_data:
  osticket_data:
        